(function(){'use strict';
const $=s=>document.querySelector(s), cvs=$('#stage'), ctx=cvs.getContext('2d'), W=cvs.width, H=cvs.height, L=['D','F','J','K'], X=[90,230,390,530], C=['#7ee7ff','#f6c453','#ff7bd5','#8ef58b'];
const save=(()=>{for(const k of ['wendao_save_v3','wendao_save_v2']){try{const v=JSON.parse(localStorage.getItem(k)||'null');if(v)return v;}catch(_){}}return {char:{realmId:0},minigame:{}};})();
const rid=(save.char&&save.char.realmId)||0, tier=Math.max(1,Math.min(6,Math.floor(rid/30)+1)), pool=(window.PHYSICS_BANK||[]).filter(q=>q&&q.type==='single'&&Array.isArray(q.options)&&q.options.length>=2);
const s={notes:[],score:0,combo:0,multi:1,tick:0,next:600,miss:0,hits:0,quiz:false,last:0,start:false,done:false,best:((save.minigame||{}).rhythm||{}).bestScore||0};
const audio={ctx:null};
function tone(n){if(!audio.ctx) audio.ctx=new (window.AudioContext||window.webkitAudioContext)(); const t=audio.ctx.currentTime,o=audio.ctx.createOscillator(),g=audio.ctx.createGain(); o.type=n%2?'triangle':'square'; o.frequency.value=[392,440,523.25,659.25][n]; g.gain.setValueAtTime(.001,t); g.gain.exponentialRampToValueAtTime(.12,t+.01); g.gain.exponentialRampToValueAtTime(.001,t+.22); o.connect(g).connect(audio.ctx.destination); o.start(t); o.stop(t+.23);}
function badge(v){return v>18000?'大乘':v>12000?'化神':v>7000?'元婴':v>3200?'金丹':'炼气';}
function persist(){save.minigame=save.minigame||{}; save.minigame.rhythm={bestScore:Math.max(s.best,s.score),lastScore:s.score,rank:badge(s.score),tier:tier,updatedAt:Date.now()}; try{localStorage.setItem(localStorage.getItem('wendao_save_v3')?'wendao_save_v3':'wendao_save_v2',JSON.stringify(save));}catch(_){}}
function ui(msg){$('#realm').textContent='境界阶差 '+tier+' / realmId '+rid; $('#rank').textContent='修为评级 '+badge(s.score); $('#score').textContent='分数 '+s.score; $('#combo').textContent='连击 '+s.combo; if(msg) $('#log').textContent=msg;}
function spawn(){s.notes.push({lane:Math.floor(Math.random()*4),y:-28,v:2.8+tier*.45});}
function quiz(){const q=pool[(Math.random()*pool.length)|0]; if(!q) return; s.quiz=true; const box=$('#quiz'), opts=$('#qopts'); $('#qtext').textContent='物理提问：'+q.q; opts.innerHTML=''; q.options.forEach(op=>{const b=document.createElement('button'); b.textContent=op; b.onclick=()=>{const ok=String(op).trim().startsWith(q.answer); s.multi=ok?Math.min(3,s.multi+.25):1; s.combo=ok?s.combo:0; ui(ok?'答对，倍率提升。':'答错，倍率重置。'); box.classList.remove('show'); s.quiz=false;}; opts.appendChild(b);}); box.classList.add('show');}
function hit(i){if(s.quiz||s.done) return; if(!s.start){s.start=true; s.last=performance.now(); ui('乐曲开始。');}
 const cand=s.notes.filter(n=>n.lane===i).sort((a,b)=>Math.abs(a.y-(H-90))-Math.abs(b.y-(H-90)))[0]; if(!cand||Math.abs(cand.y-(H-90))>44){s.combo=0; s.miss++; ui('空击。'); return;} s.notes.splice(s.notes.indexOf(cand),1); s.hits++; s.combo++; s.score+=Math.round((100+Math.min(90,s.combo*3))*s.multi); tone(i); if(s.hits%10===0) quiz(); if(s.hits>=40){s.done=true; persist(); ui('试炼完成，最高分已存。');}}
function draw(){ctx.clearRect(0,0,W,H); ctx.fillStyle='#d7b56d'; ctx.fillRect(30,H-90,W-60,4); for(let i=0;i<4;i++){ctx.fillStyle='#16233c'; ctx.fillRect(X[i]-52,0,104,H); ctx.fillStyle=C[i]; ctx.globalAlpha=.18; ctx.fillRect(X[i]-52,H-118,104,28); ctx.globalAlpha=1; ctx.fillText(L[i],X[i]-4,H-96);} s.notes.forEach(n=>{ctx.fillStyle=C[n.lane]; ctx.fillRect(X[n.lane]-34,n.y,68,18); ctx.strokeStyle='#fff'; ctx.strokeRect(X[n.lane]-34,n.y,68,18);}); ctx.fillStyle='#f3ebd2'; ctx.font='14px system-ui'; ctx.fillText('最佳 '+Math.max(s.best,s.score),20,24);}
function loop(ts){if(!s.last) s.last=ts; const dt=ts-s.last; s.last=ts; if(s.start&&!s.quiz&&!s.done){s.tick+=dt; if(s.tick>=s.next){spawn(); s.tick=0; s.next=Math.max(200,620-tier*45-Math.min(160,s.hits*3));} s.notes.forEach(n=>n.y+=n.v*dt/16.6); s.notes=s.notes.filter(n=>{if(n.y>H){s.combo=0; s.miss++; return false;} return true;}); if(s.miss>=18){s.done=true; persist(); ui('失误过多，已结算。');}} draw(); requestAnimationFrame(loop);}
addEventListener('keydown',e=>{const i=L.indexOf(e.key.toUpperCase()); if(i>-1){e.preventDefault(); hit(i);}}); ui('按 D/F/J/K 开始古乐试炼。'); requestAnimationFrame(loop);
})();
